# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bo Lu
tagline:          'Creating More Possibilities.'
description:      'Creating More <br> Possibilities.'
url:              https://lu-bo.github.io/


author:
  name:           'Bo Lu'
  email:          blu@suda.edu.cn

paginate:         3
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

# custom vars
since:                  2019
google_analytics:       UA-63207330-1
emailme:                mailto:blu@suda.edu.cn
github:
  repo:                  https://github.com/lu-bo/LuBo.github.io
version:                Jul. 28, 2025
googlescholar_username: ENPRTpcAAAAJ&hl=en
orcid_username:        0000-0002-2858-1121
#researcherid_username:  R-3094-2018 
researchgate_username:  Bo_Lu22
linkedin_username:      bo-lu-226002135/?originalSubdomain=hk
github_username:        lu-bo
share_pdf:              no
share_video:            no
# facebook_username: zrwang.cuhk
# google_plus_username: 115306810481973645007
# twitter_username: wangzerui
# instagram_username: wzr.mavericker
# cv_chn: yes